### ISSUE TITLE
sql运行出错

### ISSUE THREAD

**Issue by DaiXuYQ** [luban-h5/springboot2-jpa-api-for-luban#4]
![QQ截图20200514121637](https://user-images.githubusercontent.com/58066734/81892154-f260df00-95dc-11ea-8b5b-f78c1f0e0c3a.png)

**Comment by ly525** [comment]
@DaiXuYQ mysql 版本是多少？另外报错需要提供错误详情，截图没有截图完整

**Comment by ly525** [comment]
另外，我们本地没有复现你的问题，建议你根据错误码 1005 自行搜索

**Comment by DaiXuYQ** [comment]
![QQ截图20200514142652](https://user-images.githubusercontent.com/58066734/81900219-f990e880-95ee-11ea-8898-e4a923ceaeb6.png)

**Comment by DaiXuYQ** [comment]
我在想sql是不是有问题
![QQ截图20200514142817](https://user-images.githubusercontent.com/58066734/81900365-36f57600-95ef-11ea-9158-17578e8325db.png)
这是json类型吗

**Comment by ly525** [comment]
先回答 我的问题 mysql 版本是多少？
另外自己是否有尝试去解决这个问题？

https://zhuanlan.zhihu.com/p/19779979

**Comment by DaiXuYQ** [comment]
5.5版本，尝试了，看了文档说运行sql脚本，也报了一样的错

**Comment by ly525** [comment]
升级 mysql 到 5.7.8 以上，具体参见  https://dev.mysql.com/doc/refman/5.7/en/json.html
